title: AI note
description: AInote, a ML&DL study tutorial.
show_downloads: true
show_content: true
google_analytics:
theme: jekyll-theme-architect
github:
  repository_name: AInote 
  repository_url: https://github.com/Jiangliuer/jiangliuer.github.io
  zip_url: https://github.com/Jiangliuer/jiangliuer.github.io/archive/master.zip
  tar_url: https://github.com/Jiangliuer/jiangliuer.github.io/archive/master.zip
  is_project_page: true
  is_user_page: false
